"""Add preparation column

Revision ID: 163d34e62aa5
Revises: 6a9050cc1b32
Create Date: 2022-12-31 12:06:06.307184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163d34e62aa5'
down_revision = '6a9050cc1b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('preparation')

    # ### end Alembic commands ###
