"""Fix cascade setting

Revision ID: 23e66676c6a2
Revises: 163d34e62aa5
Create Date: 2022-12-31 16:15:07.676420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e66676c6a2'
down_revision = '163d34e62aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('ingredient_recipe_id_fkey', type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('ingredient_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
